apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-slackbot.fullname" . }}-secrets
  labels:
    {{- include "mcp-slackbot.labels" . | nindent 4 }}
type: Opaque
data:
  slack-bot-token: {{ .Values.secrets.slackBotToken | b64enc | quote }}
  slack-app-token: {{ .Values.secrets.slackAppToken | b64enc | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}